name: ci

on:
  push:
    paths-ignore:
    - README.md
    - LICENSE
    - readme/**
    - docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '21'
    - name: run unit test and send report
      run: |
        chmod +x gradlew
        ./gradlew :touchicon:koverXmlReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
